src/java/be/katho/infokiosk/model/Productdetail.java
package be.katho.infokiosk.model;
// Generated 8-nov-2012 14:15:18 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productdetails generated by hbm2java
 */
@Entity
@Table(name="productdetails"
    ,catalog="centricinfokiosk"
)
public class Productdetail implements java.io.Serializable {
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="detailsId", column=@Column(name="Details_Id", nullable=false) ), 
        @AttributeOverride(name="productsId", column=@Column(name="Products_Id", nullable=false) ) } )
     private ProductdetailsId id;
     
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Products_Id", nullable=false, insertable=false, updatable=false)
     private Product products;
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Details_Id", nullable=false, insertable=false, updatable=false)
     private Details details;
    
     @Column(name="Value", length=45)
     private String values;

    public Productdetail() {
    }
	
    public Productdetail(ProductdetailsId id, Product products, Details details) {
        this.id = id;
        this.products = products;
        this.details = details;
    }
    public Productdetail(ProductdetailsId id, Product products, Details details, String keyvalue) {
       this.id = id;
       this.products = products;
       this.details = details;
       this.values = keyvalue;
    }
   
    public ProductdetailsId getId() {
        return this.id;
    }
    
    public void setId(ProductdetailsId id) {
        this.id = id;
    }
    public Product getProducts() {
        return this.products;
    }
    
    public void setProducts(Product products) {
        this.products = products;
    }
    public Details getDetails() {
        return this.details;
    }
    
    public void setDetails(Details details) {
        this.details = details;
    }
    
    public String getDetail(){
        return this.details.getDetail();   
    }
    
    public String getValues() {
        return this.values;
    }
    
    public void setValues(String value) {
        this.values = value;
    }




}

web/KioskPresentation.jsp
<%-- 
    Document   : KioskPresentation
    Created on : 23-okt-2012, 18:21:32
    Author     : Jonas
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
        
 
    </body>
</html>

web/ProductInfo.jsp
<%-- 
    Document   : ProductInfo
    Created on : 25-okt-2012, 14:17:24
    Author     : Jennis
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html>
<html>
    <head>
        <link rel=StyleSheet href="CSS/ProductInfoCSS.css" type="text/css">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Productinformatie</title>
    </head>
    <body>
        <div id="Leftside">
        <div id="ImageHolder">
            <p>
                <img src="${viewproducts.getFirstPicture().getUrl()}" alt="${viewproducts.getFirstPicture().getDescription()}"/>
            </p>
        </div>
            <div id="thumbnails"></div>
        </div>
        <div id="ProductInformation"> 
         <h1> ${viewproducts.getName()}</h1><hr/>
         <h3>${viewproducts.getDescription()}</h3>
         <ul>
           <c:forEach items="${viewproducts.getProductdetails()}" var="Detail">
               <li>
                   ${Detail.detail} : ${Detail.values}
                   
               </li>
           </c:forEach>
       </ul> 
           <h3>Onderdeel van ${viewproducts.getCategory().getName()}</h3>
           <h2> € ${viewproducts.getPrice()}</h2>
               
        </div>
           
           
    </body>
</html>

web/ZoekenOpBarcode.jsp
<%-- 
    Document   : ZoekenOpBarcode
    Created on : 8-nov-2012, 13:55:25
    Author     : Jonas
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>KIOSK</title>
    </head>
    <body>
        <h1>Zoeken op barcode</h1>
    </body>
</html>

web/index.jsp
<%-- 
    Document   : index
    Created on : 18-okt-2012, 13:43:30
    Author     : Jonas
--%>


<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
   <body>
       <h1>Persons overview</h1>
  
   </body>
</html>